spring:
  graphql:
    graphiql:
      enabled: true      
      path: /graphiql    
    path: /graphql       
    schema:
      printer:
        enabled: true
    cors:
      allowed-origins: "*"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jwt:
  expire-timeout: 86400000
  secret-key: ${JWT_SECRET_KEY}


