spring:
  graphql:
    graphiql:
      enabled: true      
      path: /graphiql    
    path: /graphql       
    schema:
      printer:
        enabled: true
    cors:
      allowed-origins: "*"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/modul_10
    username: postgres
    password: root123
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jwt:
  expire-timeout: 86400000
  #expire-timeout: 20000
  secret-key: "hbsfghbsdhbghksjdhfjkbdshbsdjkfjksdbgksfbskdjb"


